create table
  public.users (
    username text not null,
    first text null,
    last text null,
    id bigint generated by default as identity not null,
    constraint users_pkey primary key (id),
    constraint Users_username_key unique (username),
    constraint users_id_key unique (id)
  ) tablespace pg_default;

create table
  public.events (
    id bigint generated by default as identity not null,
    active text null,
    type text null,
    name text null,
    locations text null,
    max_attendees bigint null,
    date_time timestamp without time zone null,
    constraint Event_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.brackets (
    id bigint generated by default as identity not null,
    name text null,
    active text null,
    game text null,
    capacity bigint null,
    date_time timestamp without time zone null,
    cost bigint null,
    constraint brackets_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.games (
    id bigint generated by default as identity not null,
    name text not null,
    platform text not null,
    publisher text not null,
    release_year bigint not null,
    player_count bigint not null,
    constraint games_pkey primary key (
      id,
      name,
      platform,
      publisher,
      release_year,
      player_count
    )
  ) tablespace pg_default;

create table
  public.objects (
    id bigint generated by default as identity not null,
    name text null,
    type text null,
    quantity bigint null,
    requested bigint null,
    cost bigint null,
    constraint objects_pkey primary key (id)
  ) tablespace pg_default;