create table
  public.event_items (
    event_id bigint not null,
    name text not null,
    type text null,
    requested bigint not null,
    cost bigint not null,
    delete boolean not null default false,
    constraint event_items_pkey primary key (event_id, name)
  ) tablespace pg_default;

create table
  public.events (
    id bigint generated by default as identity not null,
    active text not null,
    type text not null,
    name text not null,
    location text not null,
    max_attendees bigint not null,
    date_time timestamp without time zone not null,
    cancelled boolean not null default false,
    constraint Event_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.games (
    id bigint generated by default as identity not null,
    name text not null,
    platform text not null,
    publisher text not null,
    release_year bigint not null,
    player_count bigint not null,
    constraint games_pkey primary key (
      id,
      name,
      platform,
      publisher,
      release_year,
      player_count
    )
  ) tablespace pg_default;

create table
  public.items_ledger (
    username text not null,
    quantity bigint not null,
    payment bigint not null,
    event_id bigint not null,
    item_name text not null,
    deleted boolean not null default false,
    constraint items_ledger_pkey primary key (username, event_id, item_name),
    constraint item_ledger_event_id_item_name_fkey foreign key (event_id, item_name) references event_items (event_id, name),
    constraint item_ledger_username_fkey foreign key (username) references users (username)
  ) tablespace pg_default;

create table
  public.players (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    slot_id bigint null,
    user_id bigint null,
    constraint players_pkey primary key (id),
    constraint players_slot_id_fkey foreign key (slot_id) references slots (id) on delete cascade,
    constraint players_user_id_fkey foreign key (user_id) references users (id)
  ) tablespace pg_default;

create table
  public.users (
    username text not null,
    first text null,
    last text null,
    id bigint generated by default as identity not null,
    constraint users_pkey primary key (id),
    constraint Users_username_key unique (username),
    constraint users_id_key unique (id)
  ) tablespace pg_default;